# SPDX-License-Identifier: Apache-2.0
---
- name: Create OVN config directory
  ansible.builtin.file:
    path: /etc/ovn
    mode: "0755"
    state: directory
  when: 'ovn_roles | length > 0'

- name: Transfer OVN CA certificate
  ansible.builtin.copy:
    src: "{{ ovn_path }}/ca.crt"
    dest: /etc/ovn/{{ ovn_name }}.ca.crt
    mode: "0644"
  when: 'ovn_roles | length > 0'

- name: Transfer OVN server certificate
  ansible.builtin.copy:
    src: "{{ ovn_path }}/{{ inventory_hostname }}.crt"
    dest: /etc/ovn/{{ ovn_name }}.server.crt
    mode: "0644"
  when: 'ovn_roles | length > 0'

- name: Transfer OVN server key
  ansible.builtin.copy:
    src: "{{ ovn_path }}/{{ inventory_hostname }}.key"
    dest: /etc/ovn/{{ ovn_name }}.server.key
    mode: "0600"
  when: 'ovn_roles | length > 0'
  notify:
    - Configure OVN central northbound DB for SSL (certs)
    - Configure OVN central northbound DB for SSL (ports)
    - Configure OVN central southbound DB for SSL (certs)
    - Configure OVN central southbound DB for SSL (ports)
    - Configure OVN IC northbound DB for SSL (certs)
    - Configure OVN IC northbound DB for SSL (ports)
    - Configure OVN IC southbound DB for SSL (certs)
    - Configure OVN IC southbound DB for SSL (ports)

- name: Configure OVN central database
  ansible.builtin.template:
    src: ovn-central.j2
    dest: /etc/default/ovn-central
    mode: "0644"
  notify:
    - Restart OVN central
    - Configure OVN AZ name
    - Enable OVN IC route sharing
  when: '"central" in ovn_roles'

- name: Configure OVN host
  ansible.builtin.template:
    src: ovn-host.j2
    dest: /etc/default/ovn-host
    mode: "0644"
  notify:
    - Restart OVN host
  when: '"host" in ovn_roles'

- name: Create OVN IC override directory
  ansible.builtin.file:
    path: /etc/systemd/system/ovn-ic.service.d
    mode: "0755"
    state: directory
  when: '"ic" in ovn_roles'

- name: Transfer OVN IC override
  ansible.builtin.copy:
    content: |
      [Service]
      EnvironmentFile=-/etc/default/ovn-ic
      ExecStart=
      ExecStart=/usr/share/ovn/scripts/ovn-ctl start_ic --no-monitor $OVN_CTL_OPTS
    dest: /etc/systemd/system/ovn-ic.service.d/ansible.conf
    mode: "0644"
  notify: Restart OVN IC
  when: '"ic" in ovn_roles'

- name: Configure OVN IC database
  ansible.builtin.template:
    src: ovn-ic.j2
    dest: /etc/default/ovn-ic
    mode: "0644"
  notify:
    - Restart OVN IC databases
    - Restart OVN IC
  when: '"ic" in ovn_roles or "ic-db" in ovn_roles'

- name: Transfer OVN aliases
  ansible.builtin.template:
    src: alias.sh.j2
    dest: /etc/ovn/alias.sh
    mode: "0644"
  when: 'ovn_roles | length > 0'
