# SPDX-License-Identifier: Apache-2.0
---
- name: List installed linux images
  ansible.builtin.command: >-
    apt list linux-image-* --installed
  register: linstor_linux_image_version
  changed_when: false
  failed_when: "linstor_linux_image_version.rc != 0"
  when: '"satellite" in linstor_roles'

- name: Install linux image headers
  ansible.builtin.apt:
    name:
      - linux-headers-{{ item | regex_replace('^linux-image-(.*)/.*$', '\1') }}
    state: present
  loop: "{{ linstor_linux_image_version.stdout_lines | default([]) | select('search', 'linux-image-[0-9]+.*/.*') }}"
  when: '"satellite" in linstor_roles'

- name: Install linstor-satellite
  ansible.builtin.apt:
    name:
      - drbd-dkms
      - drbd-utils
      - linstor-satellite
      - lvm2
      - python3-setuptools
      - zfsutils-linux
    state: present
  when: '"satellite" in linstor_roles'

- name: Install linstor-controller
  ansible.builtin.apt:
    name:
      - linstor-controller
      - linstor-client
    state: present
  when: '"controller" in linstor_roles'
