# SPDX-License-Identifier: Apache-2.0
---
- name: Register all satellite hosts for every host
  ansible.builtin.set_fact:
    linstor_yaml_satellite_hosts: |-
      {% for playhost in ansible_play_hosts %}
      {% if 'satellite' in hostvars[playhost]['ansible_facts']['linstor_roles'] %}
        - "{{ playhost }}"
      {% endif %}
      {% endfor %}

- name: List storage pools
  ansible.builtin.command: linstor --machine-readable storage-pool list
  register: linstor_storage_pool_output
  changed_when: false
  when: '"controller" in linstor_roles'

- name: Parse storage pools
  ansible.builtin.set_fact:
    linstor_satellites_without_storage_pools: >-
      {{
        linstor_yaml_satellite_hosts | from_yaml | difference(
          linstor_storage_pool_output.stdout | from_json | json_query('[0][?provider_kind!=`DISKLESS`].node_name') | unique
        )
      }}
  changed_when: false
  when: '"controller" in linstor_roles'

- name: Create storage pool
  ansible.builtin.command: >-
    linstor physical-storage create-device-pool --storage-pool {{ linstor_pool_name }}
    --pool-name linstor-{{ linstor_pool_name }} {{ linstor_pool_driver }} {{ item }}
    {{ linstor_mapped_disks | join(' ') }}
  register: linstor_create_storage_pool_output
  loop: "{{ ansible_play_hosts }}"
  when: >
    ("controller" in linstor_roles) and
    ("satellite" in hostvars[item]["ansible_facts"]["linstor_roles"]) and
    (item in linstor_satellites_without_storage_pools)
  changed_when: "linstor_create_storage_pool_output.rc == 0"
